### PR TITLE
Remove 'Possible' SLIs as we have already defined a fairly comprehensive set

### PR DESCRIPTION
**Pull request by anishasthana**
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
Why not to convert this to "Implemented" SLIs instead of deleting? Why to loose track of this?

**Comment by anishasthana** [comment]
We actually have documented pretty much all of these in slightly modified forms above

- `Number of Server Spawn Operations` is captured in a useful manner under `Jupterhub Notebook Spawn Success Rate`
- `Hub Pod Restart Count` is captured in a useful manner under `Jupyterhub Main Pod Restarts`
- `Error Codes Count` is captured under `Percent of Jupyterhub Requests that are 5xx`
- `CPU Usage` and `Memory Usage` are captured with the caveat that we're' looking at _key_ Jupyterhub pods
- `Container Creation Errors (grouped by each user's pod)` is captured under `Notebook container creation errors`

**Comment by hemajv** [comment]
yep, I think all of them are already covered and they would be redundant to have

**Review by hemajv — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
